{% set name = "sphinx-automodapi" %}
{% set version = "0.8" %}
{% set git_url = "https://github.com/astropy/sphinx-automodapi" %}
{% set sha256 = "247d05ae5597ec86475e7954b788b379190a1ec0ee2f1bc60ae5086a3f29b16a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - sphinx >=1.3
  run:
    - python
    - sphinx >=1.3

test:
  imports:
    - sphinx_automodapi

about:
  home: {{ git_url }}
  license: BSD
  summary: 'Sphinx extension for auto-generating API documentation for entire modules'
  description: |
    This is a Sphinx extension to automatically generate API pages for whole
    modules.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
