{% set name = "sphinx-automodapi" %}
{% set version = "0.12" %}
{% set git_url = "https://github.com/astropy/sphinx-automodapi" %}
{% set sha256 = "a1338bc0a7f5c9bb317ecf7c7abd489c7cff452098205ef5110f733570516ac0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - sphinx >=1.7
  run:
    - python
    - sphinx >=1.7

test:
  imports:
    - sphinx_automodapi

about:
  home: {{ git_url }}
  license: BSD
  summary: 'Sphinx extension for auto-generating API documentation for entire modules'
  description: |
    This is a Sphinx extension to automatically generate API pages for whole
    modules.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
    - bsipocz
