travis:
  secure:
    BINSTAR_TOKEN: VSbQe8RWX/waHwk1uPrmjuvdxcBcK3C24SCjRvla0qv60f02Q69j3WKSR9tmxo6LneHyMLLahnlyQ4UlBHeHYrXYGuym8heahVT6fUQ7J2xM7ZPlOZZQuC7cYk/faxuuKEzAnsJJ+BJPV4LnkveJhQOtXPOLQ77AOmkiCJjWiHB1beowyfIj9EWefkoUZANSBxPQWw9Bd3pxcDi1qMg+Fmo4hQpBsNwJDc3LB+ztvLJqL+WDHoKIdoULZvqPSO6GsvxCdL947NdD8Of2g2e2XUHFpreS3oxYAwZNNDLmSPIm6nPdtc3kBDcqmqdYf6lm6Xubhs4EIVENb1/HAg1I9muY3HFL3u9wJdzfX3qYlkIbUx6qtLvhmdaqw4sBxCYhjZCnQmdBYFA3s5SUYEqONdUtLsOSRfYVGmcnaCydxMBB23aLGLoybywOrNrVivmH0lrKfYdv0s2aMEFn+IiefpsbqGVZNJDdTbDaY94FoFXlaQGo6cMzpcXDxjh6Nn0J6VJtmDhyzcrQ8zjB2PHySxo5bMo0QIk0Hh0RZ91EjSuk2EQ5gQ6aZzbtbwM0Zy3jFl3uMDUCdG1u0qxzTpeC4MSXdxBe6Dzh7KjhCnbaA+Q3+lGeOqqZ8XcEJPAvBQgnMz/ToeP2ybnX/rlclXEYOLPhGPqWv58ZWCjsj/vpojo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
