travis:
  secure:
    BINSTAR_TOKEN: NI6XoSWiMS6ySfPRVPPAsGjyKAQZYjaZis+ccmtAFH2fvMvpS+Lnt5U7oVoex6DIp7l/n/3hou2Jt4uPFnyEQ6U4sHNoJpe9bDNBaiKHQeshX68Vdlycyt0ADetJbSNPph5dsb/OSZB+j4wzevBN/m2TLM94gBJwuITWtEOrByGuf09OHytzi9jH1d3Oxp5a/thtT2p1XX5BJT2YJ6YDL1dHpOwrot6RyqD712aF5hEsAcXx1VfcDtQgKCVc7uOi67HHxxk+Ojip20FFfselaRgMhQMrUWdL4tPgqz6oIAzAIzlQChXTtYZ/BYNZlDGsERxJ19ufCE2ZTfX6da2dlFIT3JRDyPy4ixP0rEU48VYIEP0qZQArgjt2s9NBUQlXuTcSR/EI8rUHg+/6B2qF0jcjGV5JCyum7PLYPdxLGrw4QISCUH3ES+d89XlN1/sMb2zYTs9I2/66T3l45nM33FE7B9ZTnbbuU0bEWhabTtnE2U4fqkWlwRXnXz9VQcnY2s7d3/1S23ZQU5bdAzGiVFbtRj2qj+e+7hvy/67/zjCTXFW222+cmrSv9W5ylWIgLqWIzXmKJJET3XUYCUpjK0K3JDllKFPf1BDBjvdrBCW5d/ESnHo5CBe/f1CTEh6h1iy66P7olzrxspTdp8OdAgSZI02m59zExdFr0uxCgik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
